[agent]
SERVER_URL = ws://control-plane:8000/agent
SECURITY_KEY =

[runtime.container]
DRIVER = container
SAVE_PATH = /srv/dst/saves
SERVER_PATH = /srv/dst/server
UGC_PATH = /srv/dst/workshop
SERVER_MODE = 64
CONTAINER_ENGINE = docker
CONSOLE_SOCKET = /run/dst-admin/tmux/tmux.sock
CONSOLE_SESSION = dst
