RUN_MODE = release
SETUP = incomplete

[server]
HTTP_PORT = 8000
READ_TIMEOUT = 60
WRITE_TIMEOUT = 60
SECURITY_KEY =

[app]
PAGE_SIZE = 20
JWT_SECRET =

[database]
TYPE = sqlite3
PATH = /var/lib/dst-admin/go-dont.db
TABLE_PREFIX = dont_

[paths]
DST_SAVE_PATH = /var/lib/dst-admin/unmanaged-saves
DST_BACKUP_PATH = /var/lib/dst-admin/backups
DST_SERVER_PATH = /var/lib/dst-admin/unmanaged-server
DST_UGC_PATH = /var/lib/dst-admin/unmanaged-ugc
DST_MAP_PATH = /var/lib/dst-admin/maps
DST_SERVER_MODE = 64

[mod]
APP_ID = 322330
STEAM_CMD_PATH = /usr/games/steamcmd
STEAM_WEB_API_KEY =
LUA_BINARY = lua
PYTHON_BINARY = python3
LUA_SH_PATH =
WORKSHOP_MOD_PATH = /var/lib/dst-admin/workshop
WORKSHOP_CONTENT = /var/lib/dst-admin/workshop/steamapps/workshop/content/322330

[map]
RENDERER_PATH = /usr/local/bin/dst-map-renderer

[misc]
LOG_LEVEL = info

[backup]
AUTO_BACKUP = true
FREQUENCY = daily
TIME = 10:00
RETENTION = 7
