# debug or release
RUN_MODE = debug
SETUP    = complete

[app]
PAGE_SIZE  = 10
JWT_SECRET = 23347$040412

[server]
HTTP_PORT     = 8000
READ_TIMEOUT  = 60
WRITE_TIMEOUT = 60
SECURITY_KEY  = TH+MpZEZ17ng35/b6r6n+3Pi04b6AKAkSFRAs1EIaGc=

# [database]
# TYPE = mysql
# USER = dont
# PASSWORD = 001011
# #127.0.0.1:3306
# HOST = 192.168.2.12:3306
# NAME = dont
# TABLE_PREFIX = dont_
[database]
TYPE         = sqlite3
# NAME = dont
PATH         = ./go-dont.db
TABLE_PREFIX = dont_
